apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
spec:
  type: NodePort
  selector:
    app: deploy-web
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    # Kubernetes will dynamically allocate a port in the 30000-32767 range,
    # or you can optionally define a specific one (e.g. nodePort: 30080).
