apiVersion: v1
kind: Pod
metadata:
  name: pod-storage-dynamic
spec:
  containers:
  - name: app-container
    image: nginx:1.25-alpine
    volumeMounts:
    - name: data-vol
      mountPath: /data
  volumes:
  - name: data-vol
    persistentVolumeClaim:
      claimName: pvc-dynamic-demo
