apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  # 'super-secret-token' in base64:
  API_TOKEN: c3VwZXItc2VjcmV0LXRva2Vu
  # 'my-secret-password' in base64:
  DB_PASSWORD: bXktc2VjcmV0LXBhc3N3b3Jk
